# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff25ebe8f2f8b1214914a8bc6aab4fc0acd1e39b68f080fc54e1838492943eff5bf1593048580211ddeba120679f405fbf1fe4dc728bda1d9b079e1dc83d39b

test:
  secret_key_base: 0834896fadd874ba770a8a995c14e107103de3176aa9e832c5694e8f8aa663930a5ace64b95e5a6d7d78c1bc83e2d6ec8d3f1b87759773a15f7cbf30be14376b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
